manifest:
  remotes:
    - name: gabrielgg4
      url-base: https://github.com/gabrielgg4
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: gabrielgg4
      revision: main
      import: app/west.yml
      - name: zmk-dongle-display
      remote: englmaxi
      revision: main
  self:
    path: config
