manifest:
  remotes:
    - name: gabrielgg4
      url-base: https://github.com/gabrielgg4
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: gabrielgg4
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
  self:
    path: config
